### ISSUE TITLE
The function signature does not include the "function" keyword

### ISSUE THREAD

**Issue by johnson86tw** [PurrProof/calldata-visualizer#1]
Hi, I suggest removing the “function” keyword before the function name in the function signature input for clarity and accuracy.​

<img width="428" alt="截圖 2024-09-15 晚上10 21 14" src="https://github.com/user-attachments/assets/8b477157-9b73-4da7-bb10-09bb2ce474de">

Btw, this is an awesome website. I found it by reading this article https://www.rareskills.io/post/abi-encoding

Nice work!

**Comment by PurrProof** [comment]
Hi,
Thank u for the issue.
I was thinking about that too, will fix.

**Comment by PurrProof** [comment]
done
